### ISSUE TITLE
quiz is already filled out

### ISSUE THREAD

**Issue by Saturn226** [learn-co-curriculum/git-collaboration-quiz#6]
Quiz answers are pre-filled out @aturkewi

**Comment by sgharms** [comment]
Hi, @Saturn226 : generally people experience this resource via the http://learn.co platform where this README is turned into a quiz-like look-and-feel. You're kinda "peeking behind the curtains" here. There's no way to really accommodate this request for us – we need to keep that quiz working. As such, I'm going to close this issue as "working as designed."
