### ISSUE TITLE
Quiz is buggy

### ISSUE THREAD

**Issue by jaredkgrove** [learn-co-curriculum/git-collaboration-quiz#7]
I completed "Git Collaboration Quiz" without any issues. I began the "Git Basics Quiz", but jumped back to the "Git Collaboration" lesson for reference. When I returned to "Git Basics Quiz" the first question was already answered and I wasn't allowed to select answers for the next question. I refreshed my browser and now half of the answers are completed and I can only select answers for some of the other questions.
[Git Collaboration Quiz.docx](https://github.com/learn-co-curriculum/git-collaboration-quiz/files/2954316/Git.Collaboration.Quiz.docx)

**Comment by drakeltheryuujin** [comment]
Hi @jaredkgrove! 
This request sounds like a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
